# This file was generated by GoReleaser. DO NOT EDIT.
cask "gokg" do
  version "0.1.0-alpha.3"

  on_macos do
    on_intel do
      sha256 "0792ba46caaf58f5ffaaed71396f2905eb2ee8446b1a3c8d8b778812b62d6a4c"
      url "https://github.com/hungpdn/gokg/releases/download/v#{version}/gokg_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b6d735bd26b86e829a6a3524f2b06d1c94666053b7c7b86079e5a33da3a35ac8"
      url "https://github.com/hungpdn/gokg/releases/download/v#{version}/gokg_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "39d9258eaec7d793afdb65c769abeb2a372edc891340a06bbacb3ffb9d0dd31c"
      url "https://github.com/hungpdn/gokg/releases/download/v#{version}/gokg_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "35f00590371d1e03c4a00398ce4e03c1257628abe7641c0990ffa056e0b021cb"
      url "https://github.com/hungpdn/gokg/releases/download/v#{version}/gokg_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gokg"
  desc "Go-native knowledge graph and MCP server for Go codebases"
  homepage "https://github.com/hungpdn/gokg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gokg"

  # No zap stanza required

end
