# This file was generated by GoReleaser. DO NOT EDIT.
cask "gokg" do
  version "0.1.0-alpha.2"

  on_macos do
    on_intel do
      sha256 "3bba02cfbd8691649657245a0fc2cbc50d8025851c4adf8d74b11001cf5d7ea4"
      url "https://github.com/hungpdn/gokg/releases/download/v#{version}/gokg_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bdb596f2df41fc5ab0c211b1443737ee5e6895903366b91ce53c82710aa03777"
      url "https://github.com/hungpdn/gokg/releases/download/v#{version}/gokg_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0f7816f1886a8535b097cd785f54fdce609f135e428c90c4c053e4ccf6fa6d09"
      url "https://github.com/hungpdn/gokg/releases/download/v#{version}/gokg_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "039a1acead1daa7a07465ca90abf5f46dcd0603b3e2e773574c5d98098f713b5"
      url "https://github.com/hungpdn/gokg/releases/download/v#{version}/gokg_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gokg"
  desc "Go-native knowledge graph and MCP server for Go codebases"
  homepage "https://github.com/hungpdn/gokg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gokg"

  # No zap stanza required

end
