# This file was generated by GoReleaser. DO NOT EDIT.
cask "gokg" do
  version "0.1.0-alpha.4"

  on_macos do
    on_intel do
      sha256 "77de1b431b6977cfdc4ceeb333826c27bc8628191e36752c826e1b4c43493251"
      url "https://github.com/hungpdn/gokg/releases/download/v#{version}/gokg_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a2d71f37ea9f363d52d22bcc0e361afdb2f8d38b9b7c149f3f56f8aa67d3d72e"
      url "https://github.com/hungpdn/gokg/releases/download/v#{version}/gokg_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b7ff6f806f3f9dc9f49321544fabe6049b6875462e829020be927bbe9356f3c4"
      url "https://github.com/hungpdn/gokg/releases/download/v#{version}/gokg_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9f0240e552bd5a518b83ebe24da33e459da9e2a686ded8d892d463329d32604f"
      url "https://github.com/hungpdn/gokg/releases/download/v#{version}/gokg_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gokg"
  desc "Go-native knowledge graph and MCP server for Go codebases"
  homepage "https://github.com/hungpdn/gokg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gokg"

  # No zap stanza required

end
